Repository pbdsce/iict-hack, pull requests merged in 2025-08, with the labels that each got.

#11 refactor: Update font family from Monotype Corsiva to Times New Roman…
  app/ConditionalNavbar.tsx
  app/favicon.ico
  app/globals.css
  app/layout.tsx
  app/page.tsx
  components/landing/FAQ.tsx
  components/landing/Hero.tsx
  components/landing/Sponsors.tsx
  components/landing/Themes.tsx
  components/landing/Timeline.tsx
  components/register/RegistrationForm.tsx
  components/register/TeamProfessionalProfilesStep.tsx
  components/ui/footer.tsx
  components/ui/navbar.tsx
  next.config.ts
  package-lock.json
  public/images/default.svg
  public/images/variant.svg
  tailwind.config.js
Labels: Frontend, Dependencies, size-XL, Styling, Config

#13 add google analytics to the landing page
  app/layout.tsx
  package-lock.json
Labels: Frontend, size-S, Dependencies

#14 add analytics to registration page
  app/register/layout.tsx
Labels: Frontend, size-S
